# Generated by Django 3.0.5 on 2020-05-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificateForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=20)),
                ('cellTech', models.CharField(max_length=20)),
                ('cellManuf', models.CharField(max_length=20)),
                ('numCells', models.CharField(max_length=20)),
                ('numCellsSeries', models.CharField(max_length=20)),
                ('numSeriesStrings', models.CharField(max_length=20)),
                ('numDiodes', models.CharField(max_length=20)),
                ('prodLength', models.CharField(max_length=20)),
                ('prodWidth', models.CharField(max_length=20)),
                ('superstrateType', models.CharField(max_length=20)),
                ('superstrateManuf', models.CharField(max_length=20)),
                ('substrateType', models.CharField(max_length=20)),
                ('substrateManuf', models.CharField(max_length=20)),
                ('frameType', models.CharField(max_length=20)),
                ('frameAdhesive', models.CharField(max_length=20)),
                ('encapsulantType', models.CharField(max_length=20)),
                ('encapsulatManuf', models.CharField(max_length=20)),
                ('junctionBoxType', models.CharField(max_length=20)),
                ('junctionBoxManuf', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testStandName', models.CharField(max_length=20)),
                ('testStandDesc', models.CharField(max_length=255)),
                ('testStandPubDate', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificateForm.Question'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=10)),
                ('address2', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('postalCode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('faxNumber', models.CharField(max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificateForm.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certID', models.CharField(max_length=8)),
                ('reportNum', models.CharField(max_length=8)),
                ('issueDate', models.CharField(max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificateForm.Location')),
                ('modelNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificateForm.Product')),
                ('testStandard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificateForm.TestStandard')),
            ],
        ),
    ]
