# Generated by Django 3.0.5 on 2020-05-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=20)),
                ('cellTech', models.CharField(max_length=20)),
                ('cellManuf', models.CharField(max_length=20)),
                ('numCells', models.CharField(max_length=20)),
                ('numCellsSeries', models.CharField(max_length=20)),
                ('numSeriesStrings', models.CharField(max_length=20)),
                ('numDiodes', models.CharField(max_length=20)),
                ('prodLength', models.CharField(max_length=20)),
                ('prodWidth', models.CharField(max_length=20)),
                ('superstrateType', models.CharField(max_length=20)),
                ('superstrateManuf', models.CharField(max_length=20)),
                ('substrateType', models.CharField(max_length=20)),
                ('substrateManuf', models.CharField(max_length=20)),
                ('frameType', models.CharField(max_length=20)),
                ('frameAdhesive', models.CharField(max_length=20)),
                ('encapsulantType', models.CharField(max_length=20)),
                ('encapsulatManuf', models.CharField(max_length=20)),
                ('junctionBoxType', models.CharField(max_length=20)),
                ('junctionBoxManuf', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productForm.Question'),
        ),
    ]
