# Generated by Django 3.0.5 on 2020-05-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testStandardForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testStandName', models.CharField(max_length=20)),
                ('testStandDesc', models.CharField(max_length=255)),
                ('testStandPubDate', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testStandardForm.Question'),
        ),
    ]
