# Generated by Django 3.0.5 on 2020-05-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locationForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locationForm.Question'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=10)),
                ('address2', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('postalCode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('faxNumber', models.CharField(max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locationForm.Client')),
            ],
        ),
    ]
