# Generated by Django 3.0.5 on 2020-05-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200503_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientCode', models.CharField(max_length=8)),
                ('clientName', models.CharField(max_length=10)),
                ('clientType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=20)),
                ('cellTech', models.CharField(max_length=20)),
                ('cellManuf', models.CharField(max_length=20)),
                ('numCells', models.CharField(max_length=20)),
                ('numCellsSeries', models.CharField(max_length=20)),
                ('numSeriesStrings', models.CharField(max_length=20)),
                ('numDiodes', models.CharField(max_length=20)),
                ('prodLength', models.CharField(max_length=20)),
                ('prodWidth', models.CharField(max_length=20)),
                ('superstrateType', models.CharField(max_length=20)),
                ('superstrateManuf', models.CharField(max_length=20)),
                ('substrateType', models.CharField(max_length=20)),
                ('substrateManuf', models.CharField(max_length=20)),
                ('frameType', models.CharField(max_length=20)),
                ('frameAdhesive', models.CharField(max_length=20)),
                ('encapsulantType', models.CharField(max_length=20)),
                ('encapsulatManuf', models.CharField(max_length=20)),
                ('junctionBoxType', models.CharField(max_length=20)),
                ('junctionBoxManuf', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequenceName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testStandName', models.CharField(max_length=20)),
                ('testStandDesc', models.CharField(max_length=255)),
                ('testStandPubDate', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('middleName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('officePhone', models.CharField(max_length=15)),
                ('cellPhone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceID', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=255)),
                ('isFiRequired', models.CharField(max_length=3)),
                ('fiFrequency', models.CharField(max_length=10)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.TestStandard')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxSystemVolts', models.CharField(max_length=10)),
                ('voc', models.CharField(max_length=10)),
                ('isc', models.CharField(max_length=10)),
                ('vmp', models.CharField(max_length=10)),
                ('imp', models.CharField(max_length=10)),
                ('pmp', models.CharField(max_length=10)),
                ('ff', models.CharField(max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Product')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.TestSequence')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=10)),
                ('address2', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('postalCode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('faxNumber', models.CharField(max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certID', models.CharField(max_length=8)),
                ('reportNum', models.CharField(max_length=8)),
                ('issueDate', models.CharField(max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Location')),
                ('modelNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Product')),
                ('testStandard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.TestStandard')),
                ('user', models.ManyToManyField(to='dashboard.User')),
            ],
        ),
    ]
